class ModuleDefinition {
  const ModuleDefinition(this.name,this.endpoint,this.description);
  final String name; final String endpoint; final String description;
}
const moduleCatalog=<ModuleDefinition>[
  ModuleDefinition('Destinations','/destinations','Destination discovery and management'),
  ModuleDefinition('Tours','/tours','Tours, pricing and availability'),
  ModuleDefinition('Bookings','/bookings','Customer booking lifecycle'),
  ModuleDefinition('Reviews','/reviews','Reviews and moderation'),
  ModuleDefinition('Wishlist','/wishlist','Customer saved experiences'),
  ModuleDefinition('Gallery','/gallery','Travel media'),
  ModuleDefinition('Categories','/categories','Tour categories'),
  ModuleDefinition('Hotels','/hotels','Hospitality inventory'),
  ModuleDefinition('Airport Transfers','/airport-transfers','Airport transfer services'),
  ModuleDefinition('Hospitality Payments','/hospitality-payments','Hospitality payment lifecycle'),
  ModuleDefinition('Vehicles','/vehicles','Fleet and operational assets'),
  ModuleDefinition('Guides','/guide','Guide operations'),
  ModuleDefinition('Drivers','/driver','Driver operations'),
  ModuleDefinition('Agents','/agents','Agent operations'),
  ModuleDefinition('Agent Customers','/agents/customers','Agent CRM'),
  ModuleDefinition('Agent Packages','/agents/packages','Agent packages'),
  ModuleDefinition('Agent Quotes','/agents/quotes','Quotations'),
  ModuleDefinition('Commissions','/commissions','Commission accounting'),
  ModuleDefinition('Customers CRM','/admin/customers','Customer relationship management'),
  ModuleDefinition('Invoices','/invoices','Invoice lifecycle'),
  ModuleDefinition('Notifications','/notifications','Customer and staff notifications'),
  ModuleDefinition('Operations','/admin/operations','Procurement and operations'),
  ModuleDefinition('Analytics','/analytics','Operational analytics'),
  ModuleDefinition('Finance','/admin/finance','Accounting, reports and reconciliation'),
  ModuleDefinition('Compliance','/admin/compliance','Compliance and eTIMS'),
  ModuleDefinition('Tax','/admin/tax','Kenya tax rules and calculations'),
  ModuleDefinition('Payment Gateways','/admin/payment-gateways','Tenant payment gateway configuration'),
  ModuleDefinition('Developer Platform','/admin/developer','API keys and webhooks'),
  ModuleDefinition('Settings','/admin/settings','Tenant configuration and branding'),
  ModuleDefinition('System Health','/admin/system-health','Protected operational health'),
  ModuleDefinition('AI','/ai','AI assistants and recommendations'),
  ModuleDefinition('Custom Tours','/custom-tour-requests','Custom tour requests'),
  ModuleDefinition('SuperAdmin','/superadmin','Platform administration'),
];
